# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

# github told me to use rouge
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : roger allen
tagline: Come up with a great tagline here.
author :
  name : Roger Allen
  github : rogerallen
  twitter : RogerAllen
  mstdn : rogerallen

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url : https://rogerallen.github.io

markdown: kramdown
excerpt_separator: "<!--more-->"

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

google_analytics: UA-36720141-1
